"""First-party plugins shipped with fastauth."""

from __future__ import annotations

from fastauth.plugins.base import (
    Capability,
    EndpointHookSpec,
    EndpointInfo,
    EndpointSpec,
    Plugin,
    PluginApiNamespace,
    PluginApiRegistry,
    PluginErrorCode,
    PluginInfo,
    PluginMiddlewareSpec,
    PluginOptions,
    PluginRegistry,
    RateLimitRule,
    RequestHookSpec,
    ResponseHookSpec,
)
from fastauth.plugins.migrations import (
    MigrationOperation,
    PlannedMigration,
    PlannedTable,
    PluginMigrationFingerprintError,
    PluginMigrationMode,
    PluginMigrationPendingError,
    PluginMigrationRecord,
    PluginMigrationResult,
    PluginSchemaConflictError,
    PluginSchemaPlan,
    SchemaConflict,
    build_schema_plan,
    build_schema_plan_from_registry,
    render_migration_operations,
)
from fastauth.plugins.schema import (
    FieldSpec,
    IndexSpec,
    MigrationSpec,
    PluginFieldType,
    PluginSchema,
    TableSpec,
)

__all__ = [
    "Capability",
    "EndpointHookSpec",
    "EndpointInfo",
    "EndpointSpec",
    "FieldSpec",
    "IndexSpec",
    "MigrationOperation",
    "MigrationSpec",
    "PlannedMigration",
    "PlannedTable",
    "Plugin",
    "PluginApiNamespace",
    "PluginApiRegistry",
    "PluginErrorCode",
    "PluginFieldType",
    "PluginInfo",
    "PluginMiddlewareSpec",
    "PluginMigrationFingerprintError",
    "PluginMigrationMode",
    "PluginMigrationPendingError",
    "PluginMigrationRecord",
    "PluginMigrationResult",
    "PluginOptions",
    "PluginRegistry",
    "PluginSchema",
    "PluginSchemaConflictError",
    "PluginSchemaPlan",
    "RateLimitRule",
    "RequestHookSpec",
    "ResponseHookSpec",
    "SchemaConflict",
    "TableSpec",
    "build_schema_plan",
    "build_schema_plan_from_registry",
    "render_migration_operations",
]
